### PR TITLE
Spanish localization

### PR DESCRIPTION
**Pull request by axiel7**

### CODE REVIEW

**Comment by superhighfives** [comment]
Thanks so much for sharing, @axiel7! Will take a look at integrating this in the next major version. 👍

**Comment by axiel7** [comment]
No problem! Feel free to ping me for new strings updates

**Comment by superhighfives** [comment]
This is now released as `0.0.16-beta1`, which you can access by downloading it from https://github.com/superhighfives/pika/releases/tag/0.0.16-beta1, or by checking "Subscribe to beta releases" in Pika's settings and then "Check for updates..." in the menu. Thank you so uch, @axiel7!

Any feedback or issues, please let me know.

**Comment by axiel7** [comment]
Just installed it and everything looks fine! Your welcome and thank you for the great app!

**Pull request merged**
