### PR TITLE
0.0.13

### PR DESCRIPTION
**Pull request by superhighfives**

### CODE REVIEW

**Comment by superhighfives** [comment]
@AClmbr, I was wondering if you'd be able to help out by taking a look at the changes / additions for the French language in this one? No worries at all if not. 👍

**Comment by AClmbr** [comment]
Yes sure, just give me a few days please and it will be done 👍

**Comment by AClmbr** [comment]
Hi @superhighfives,
I got the code but every time I try to run the project the app crashes.
The console says:
```
dyld: Library not loaded: @rpath/Sparkle.framework/Versions/A/Sparkle
Referenced from: [...]/Xcode/DerivedData/Pika-afaujgwakryiryagrrwfvnpghsuk/Build/Products/Debug/Pika.app/Contents/MacOS/Pika
Reason: no suitable image found
```
Do you have any idea why?

**Comment by superhighfives** [comment]
Hmmm, sorry to hear that—guessing it's something to do with packages not being resolved correctly. Could you try resolving the package versions? If that doesn't work, you could try resetting the package caches?

image

**Comment by AClmbr** [comment]
Nothing worked...
In the console, in addition to what I said last time, I also get this :
```
[...]/Frameworks/Sparkle.framework/Versions/A/Sparkle) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)
```
I think it's more related to the Sparkle image 🤔

**Comment by superhighfives** [comment]
Ah, I wonder if it's something to do with the signing. 🤔 

What do you see if you tap the Project and then the target? It may be tied to my "team", which you wouldn't have the ability to sign for.

image

**Pull request merged**
