### PR TITLE
#128 fix hovering issue of swap button

### PR DESCRIPTION
**Pull request by travisbikkle**
`ContentView.swift`

```swift
ColorPickers()
                 .onHover { hover in
                     if hover {
                         swapVisible = true
                         timerSubscription?.cancel()
                         timerSubscription = nil
                     } else {
                         if self.timerSubscription == nil {
                             self.timer = Timer.publish(every: 0.25, on: .main, in: .common)
                             self.timerSubscription = self.timer.connect()
                         }
                     }
                 }
                 .onReceive(timer) { _ in
                     swapVisible = false
                     timerSubscription?.cancel()
                     timerSubscription = nil
                 }
                 .overlay(
                     Button(action: {
                         NSApp.sendAction(#selector(AppDelegate.triggerSwap), to: nil, from: nil)
```

The swap button between two eyedroppers could never show alt text, because this button is on an overlay layer, hovering on this button leads to not hovering on `ColorPickers()`. After 0.25 seconds, `swapVisible` will be false, this button would be hidden, but at this time SwapButtonStyle is just about to show the alt text.

### CODE REVIEW

**Comment by travisbikkle** [comment]
fixed:

Screenshot 2024-09-26 at 01 57 44

**Comment by travisbikkle** [comment]
I have noticed that @superhighfives had changed the ui of those buttons to adapt to the system picker feature in 0.0.18 pr.
This fix does not conflict with those changes, I've tested it.

**Review by superhighfives — APPROVED** [review]
Awesome, looks good. 👍

**Comment by superhighfives** [comment]
Thanks for submitting, @travisbikkle!

**Comment by travisbikkle** [comment]
> Thanks for submitting, @travisbikkle!

Glad to help.

**Pull request merged**
