### PR TITLE
0.0.11

### PR DESCRIPTION
**Pull request by superhighfives**

### CODE REVIEW

**Comment by superhighfives** [comment]
Hey @AClmbr—I've made some updates to the French localization strings, and I was keen to get your thoughts on if they're okay translations. The primary ones are "Export", "System Default", and "Copy all as text" / "JSON". The color names addition is all English, as there is no translation, but I've made them hidable given that.

Otherwise I think this is good to go for beta. Really appreciate all your help!

**Comment by AClmbr** [comment]
Do you want me to check the translations or everything is ok? 😊

**Comment by superhighfives** [comment]
If you don't mind, that'd be awesome @AClmbr. I also added "Pass" and "Fail" in there too. Just wasn't 100% on whether the things I added made sense in French.

Appreciate it! 🙌

**Comment by AClmbr** [comment]
```
/* Pass */
"color.wcag.pass" = "Passe";

/* Fail */
"color.wcag.pass" = "Échouer";
```

These ones aren't used?

**Pull request merged**
